alertmanagerSpec:
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

  route:
    receiver: "default"
    group_by: ["alertname"]
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 3h

  receivers:
    - name: "default"
      email_configs:
        - to: "your-email@example.com"
          send_resolved: true
